const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={time:3600,fear:22,muted:false,items:[['⚿','Chiave d’ottone'],['◍','Sigillo solare'],['▧','Pagina cifrata']],seen:new Set(),clues:0,hints:2};
const inspectData={desk:{title:'Scrivania del professore',text:'Tra appunti astronomici e formule cancellate trovi una pagina con tre costellazioni cerchiate.',action:'Raccogli la pagina'},globe:{title:'Globo meccanico',text:'L’equatore è inciso con simboli. Tre anelli possono ruotare separatamente.',action:'Ruota gli anelli'},cabinet:{title:'Vetrina delle reliquie',text:'Una serratura a quattro dischi protegge un piccolo sigillo di bronzo.',action:'Esamina i dischi'},door:{title:'Porta dell’archivio',text:'Tre alloggiamenti vuoti circondano la serratura. Servono altrettanti sigilli.',action:'Controlla i sigilli'}};
function vibrate(p=15){navigator.vibrate?.(p)}
function render(){const m=String(Math.floor(state.time/60)).padStart(2,'0'),s=String(state.time%60).padStart(2,'0');$('#timer').textContent=`${m}:${s}`;$('#fearValue').textContent=`${state.fear}%`;$('#fearBar').style.width=`${state.fear}%`;$('#inventoryCount').textContent=`${state.items.length} / 6`;$('#inventorySlots').innerHTML=[...state.items,...Array(Math.max(0,6-state.items.length)).fill(null)].map(x=>x?`<button class="slot filled" title="${x[1]}">${x[0]}</button>`:'<div class="slot"></div>').join('')}
setInterval(()=>{if(state.time>0){state.time--;render()}},1000);
function closeInspect(){$('#inspect').classList.remove('open');$('#inspect').setAttribute('aria-hidden','true')}
function openInspect(type){const d=inspectData[type];$('#inspectTitle').textContent=d.title;$('#inspectText').textContent=d.text;$('#inspectArt').dataset.type=type;$('#inspectActions').className='inspect-actions';$('#inspectActions').innerHTML=`<button>${d.action}</button>`;$('#inspect').classList.add('open');$('#inspect').setAttribute('aria-hidden','false');if(!state.seen.has(type)){state.seen.add(type);state.clues++;state.fear=Math.min(100,state.fear+2)}render();vibrate(18);$('#inspectActions button').onclick=()=>{if(type==='desk'){$('#objectiveText').textContent='Usa le costellazioni per allineare il globo meccanico.'}if(type==='globe'&&state.seen.has('desk')){$('#objectiveText').textContent='Il globo ha rivelato il codice 3-1-4. Provalo sulla vetrina.';if(!state.items.some(i=>i[1]==='Sigillo lunare'))state.items.push(['◐','Sigillo lunare'])}if(type==='cabinet'&&state.seen.has('globe')){$('#objectiveText').textContent='Hai due sigilli. Il terzo è nascosto nella stanza.';if(!state.items.some(i=>i[1]==='Sigillo del corvo'))state.items.push(['◆','Sigillo del corvo'])}if(type==='door'&&state.items.filter(i=>i[1].includes('Sigillo')).length>=3){$('#objectiveText').textContent='La porta dell’archivio è sbloccata.';state.fear=Math.min(100,state.fear+8)}render();closeInspect()}}
$$('.hotspot').forEach(b=>b.onclick=()=>openInspect(b.dataset.type));$('#closeInspect').onclick=closeInspect;$('#inspectBackdrop').onclick=closeInspect;
$('#flash').onclick=()=>{document.body.classList.toggle('flash-on');vibrate(10)};$('#sound').onclick=()=>{state.muted=!state.muted;$('#sound').textContent=state.muted?'🔇':'🔊'};
function panelContent(type){if(type==='diary')return ['DIARIO',`<div class="sheet-item"><small>NUOVA VOCE</small><b>Il professor Voss</b><p>«La porta non protegge l’archivio da voi. Protegge voi da ciò che è custodito dentro.»</p></div><div class="sheet-item"><small>INDIZI TROVATI</small><b>${state.clues} / 18</b></div>`];if(type==='inventory')return ['INVENTARIO',`<div class="sheet-grid">${state.items.map(x=>`<div class="sheet-item"><small>OGGETTO</small><b>${x[0]} ${x[1]}</b></div>`).join('')}</div>`];if(type==='hints')return ['AIUTI',`<div class="sheet-grid"><div class="sheet-item"><small>DISPONIBILI</small><b>${state.hints}</b></div><div class="sheet-item"><small>PROGRESSI</small><b>${state.clues}/18</b></div></div><button id="useHint" class="hint-mini" style="width:100%;border-radius:4px;margin-top:14px">Usa un aiuto</button>`];return ['ALTRO','<div class="sheet-grid"><div class="sheet-item"><small>QUALITÀ</small><b>Alta</b></div><div class="sheet-item"><small>VIBRAZIONE</small><b>Attiva</b></div><div class="sheet-item"><small>AUDIO</small><b>Spaziale</b></div><div class="sheet-item"><small>SALVATAGGIO</small><b>Automatico</b></div></div>']}
function openSheet(type){if(type==='game'){closeSheet();return}const [title,html]=panelContent(type);$('#sheetTitle').textContent=title;$('#sheetBody').innerHTML=html;$('#sheet').classList.add('open');$('#sheet').setAttribute('aria-hidden','false');$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.panel===type));$('#useHint')?.addEventListener('click',()=>{if(state.hints>0){state.hints--;closeSheet();$('#inspectTitle').textContent='Suggerimento';$('#inspectText').textContent='Le costellazioni segnate sulla pagina indicano l’ordine con cui ruotare gli anelli del globo.';$('#inspectActions').innerHTML='<button>Ho capito</button>';$('#inspectActions button').onclick=closeInspect;$('#inspect').classList.add('open');render()}})}
function closeSheet(){$('#sheet').classList.remove('open');$('#sheet').setAttribute('aria-hidden','true');$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.panel==='game'))}
$$('.bottom-nav button').forEach(b=>b.onclick=()=>openSheet(b.dataset.panel));$('#closeSheet').onclick=closeSheet;$('#sheetBackdrop').onclick=closeSheet;$('#hintQuick').onclick=()=>openSheet('hints');
function eventLoop(){setTimeout(()=>{if(!document.hidden){document.body.classList.add('flash-on');setTimeout(()=>document.body.classList.remove('flash-on'),180);vibrate([10,35,16]);state.fear=Math.min(100,state.fear+1);render()}eventLoop()},11000+Math.random()*19000)}eventLoop();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));render();