const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={time:3600,fear:22,muted:false,items:[['⚿','Chiave d’ottone'],['◍','Sigillo solare'],['▧','Pagina cifrata']],seen:new Set(),completed:new Set(),clues:0,hints:2};
const inspectData={desk:{title:'Scrivania del professore',text:'Tra appunti astronomici e formule cancellate trovi una pagina con tre costellazioni cerchiate.',action:'Studia le costellazioni'},globe:{title:'Globo meccanico',text:'L’equatore è inciso con simboli. Tre anelli possono ruotare separatamente.',action:'Allinea gli anelli'},cabinet:{title:'Vetrina delle reliquie',text:'Una serratura a quattro dischi protegge un piccolo sigillo di bronzo.',action:'Prova il codice'},door:{title:'Porta dell’archivio',text:'Tre alloggiamenti vuoti circondano la serratura. Servono altrettanti sigilli.',action:'Inserisci i sigilli'}};
function vibrate(p=15){navigator.vibrate?.(p)}
function sealCount(){return state.items.filter(i=>i[1].includes('Sigillo')).length}
function render(){const m=String(Math.floor(state.time/60)).padStart(2,'0'),s=String(state.time%60).padStart(2,'0');$('#timer').textContent=`${m}:${s}`;$('#fearValue').textContent=`${state.fear}%`;$('#fearBar').style.width=`${state.fear}%`;$('#inventoryCount').textContent=`${state.items.length} / 6`;$('#clueCount').textContent=`${state.clues} / 4`;$('#sealCount').textContent=`${sealCount()} / 3`;$('#inventorySlots').innerHTML=[...state.items,...Array(Math.max(0,6-state.items.length)).fill(null)].map(x=>x?`<button class="slot filled" title="${x[1]}">${x[0]}</button>`:'<div class="slot"></div>').join('')}
setInterval(()=>{if(state.time>0){state.time--;render()}},1000);
function closeInspect(){$('#inspect').classList.remove('open');$('#inspect').setAttribute('aria-hidden','true')}
function openInspect(type){const d=inspectData[type];$('#inspectTitle').textContent=d.title;$('#inspectText').textContent=d.text;$('#inspectArt').dataset.type=type;$('#inspectActions').className='inspect-actions';$('#inspectActions').innerHTML=`<button>${d.action}</button>`;$('#inspect').classList.add('open');$('#inspect').setAttribute('aria-hidden','false');if(!state.seen.has(type)){state.seen.add(type);state.clues=Math.min(4,state.clues+1);state.fear=Math.min(100,state.fear+2)}render();vibrate(18);$('#inspectActions button').onclick=()=>resolveInteraction(type)}
function resolveInteraction(type){if(type==='desk'){state.completed.add('desk');$('#objectiveText').textContent='Usa l’ordine delle costellazioni sul globo meccanico.'}else if(type==='globe'){if(!state.completed.has('desk'))return showMessage('Manca un indizio','Gli anelli non hanno senso senza conoscere l’ordine corretto.');state.completed.add('globe');if(!state.items.some(i=>i[1]==='Sigillo lunare'))state.items.push(['◐','Sigillo lunare']);$('#objectiveText').textContent='Il globo mostra il codice 3-1-4. Usalo sulla vetrina.'}else if(type==='cabinet'){if(!state.completed.has('globe'))return showMessage('Serratura bloccata','Non conosci ancora la combinazione dei dischi.');state.completed.add('cabinet');if(!state.items.some(i=>i[1]==='Sigillo del corvo'))state.items.push(['◆','Sigillo del corvo']);$('#objectiveText').textContent='Hai tutti i sigilli. Torna alla porta dell’archivio.'}else if(type==='door'){if(sealCount()<3)return showMessage('Porta sigillata',`Hai trovato ${sealCount()} sigilli su 3.`);state.completed.add('door');$('#objectiveText').textContent='La porta dell’archivio è sbloccata.';state.fear=Math.min(100,state.fear+8)}render();closeInspect()}
function showMessage(title,text){$('#inspectTitle').textContent=title;$('#inspectText').textContent=text;$('#inspectActions').innerHTML='<button>Continua a cercare</button>';$('#inspectActions button').onclick=closeInspect;vibrate([18,35,18])}
$$('.hotspot').forEach(b=>b.onclick=()=>openInspect(b.dataset.type));$('#closeInspect').onclick=closeInspect;$('#inspectBackdrop').onclick=closeInspect;
$('#flash').onclick=()=>{document.body.classList.toggle('flash-on');vibrate(10)};$('#sound').onclick=()=>{state.muted=!state.muted;$('#sound').textContent=state.muted?'🔇':'🔊'};
function panelContent(type){if(type==='diary')return ['DIARIO',`<div class="sheet-item"><small>REGISTRAZIONE I</small><b>Il professor Voss</b><p>«La porta non protegge l’archivio da voi. Protegge voi da ciò che è custodito dentro.»</p></div><div class="sheet-item"><small>INDIZI TROVATI</small><b>${state.clues} / 4</b></div>`];if(type==='inventory')return ['INVENTARIO',`<div class="sheet-grid">${state.items.map(x=>`<div class="sheet-item"><small>OGGETTO</small><b>${x[0]} ${x[1]}</b></div>`).join('')}</div>`];if(type==='hints')return ['AIUTI',`<div class="sheet-grid"><div class="sheet-item"><small>DISPONIBILI</small><b>${state.hints}</b></div><div class="sheet-item"><small>SIGILLI</small><b>${sealCount()}/3</b></div></div><button id="useHint" class="secondary-btn" style="width:100%;margin-top:14px">Usa un aiuto</button>`];return ['ALTRO','<div class="sheet-grid"><div class="sheet-item"><small>QUALITÀ</small><b>Alta</b></div><div class="sheet-item"><small>VIBRAZIONE</small><b>Attiva</b></div><div class="sheet-item"><small>AUDIO</small><b>Spaziale</b></div><div class="sheet-item"><small>SALVATAGGIO</small><b>Automatico</b></div></div>']}
function openSheet(type){if(type==='game'){closeSheet();return}const [title,html]=panelContent(type);$('#sheetTitle').textContent=title;$('#sheetBody').innerHTML=html;$('#sheet').classList.add('open');$('#sheet').setAttribute('aria-hidden','false');$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.panel===type));$('#useHint')?.addEventListener('click',()=>{if(state.hints>0){state.hints--;closeSheet();$('#inspectTitle').textContent='Suggerimento';$('#inspectText').textContent=state.completed.has('desk')?'Prova a usare l’ordine delle costellazioni sul globo.':'Inizia dalla scrivania: gli appunti del professore sembrano collegati al globo.';$('#inspectActions').innerHTML='<button>Ho capito</button>';$('#inspectActions button').onclick=closeInspect;$('#inspect').classList.add('open');render()}})}
function closeSheet(){$('#sheet').classList.remove('open');$('#sheet').setAttribute('aria-hidden','true');$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.panel==='game'))}
$$('.bottom-nav button').forEach(b=>b.onclick=()=>openSheet(b.dataset.panel));$('#closeSheet').onclick=closeSheet;$('#sheetBackdrop').onclick=closeSheet;$('#hintQuick').onclick=()=>openSheet('hints');
function eventLoop(){setTimeout(()=>{if(!document.hidden){document.body.classList.add('flash-on');setTimeout(()=>document.body.classList.remove('flash-on'),180);vibrate([10,35,16]);state.fear=Math.min(100,state.fear+1);render()}eventLoop()},12000+Math.random()*19000)}eventLoop();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));render();