const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const SAVE='heldroom-cinematic-v4';
const state={scene:'foyer',time:3600,muted:false,items:[],tension:12,lastInput:Date.now(),timer:null,eventTimer:null,audio:null,flags:{portraitMoved:false,safeSolved:false,keyTaken:false,foyerSolved:false,crankTaken:false,recordPlayed:false,recordSolved:false,parlorSolved:false,shadowSeen:false,symbolsRead:false,corridorSolved:false,lullabyTaken:false,dollClue:false,clockSolved:false,nurserySolved:false,atticSeal:false},eventsSeen:new Set()};
const rooms={
 foyer:{chapter:'CAPITOLO I',name:'L’atrio senza luce',objective:()=>state.flags.safeSolved?'Raccogli la chiave e apri la porta':'Scopri cosa nasconde il ritratto',hotspots:[{x:23,y:42,label:'Ritratto',action:'portrait'},{x:51,y:64,label:'Bambola',action:'doll'},{x:75,y:55,label:'Porta',action:'foyerDoor'}]},
 parlor:{chapter:'CAPITOLO II',name:'Il salotto del grammofono',objective:()=>state.flags.crankTaken?'Usa la manovella e decifra il disco':'Trova il pezzo mancante del grammofono',hotspots:[{x:28,y:47,label:'Grammofono',action:'record'},{x:72,y:45,label:'Tenda',action:'curtain'},{x:51,y:72,label:'Porta',action:'parlorDoor'}]},
 corridor:{chapter:'CAPITOLO III',name:'Il corridoio delle ombre',objective:()=>state.flags.symbolsRead?'Decifra i simboli sulla porta':'Trova il codice nascosto nel corridoio',hotspots:[{x:24,y:45,label:'Quadri',action:'frames'},{x:51,y:48,label:'Ombra',action:'shadow'},{x:51,y:72,label:'Nursery',action:'corridorDoor'}]},
 nursery:{chapter:'CAPITOLO IV',name:'La nursery di Clara',objective:()=>state.flags.lullabyTaken&&state.flags.dollClue?'Regola l’orologio con gli indizi raccolti':'Trova gli indizi nella stanza',hotspots:[{x:50,y:66,label:'Bambola',action:'nurseryDoll'},{x:70,y:37,label:'Orologio',action:'clock'},{x:24,y:65,label:'Letto',action:'bed'},{x:87,y:53,label:'Botola',action:'nurseryDoor'}]},
 attic:{chapter:'CAPITOLO V',name:'La soffitta dei nomi',objective:()=>state.flags.atticSeal?'Il primo sigillo è spezzato':'Trova il nome che la casa ha cancellato',hotspots:[{x:28,y:45,label:'Baule',action:'trunk'},{x:56,y:38,label:'Cartellini',action:'names'},{x:79,y:62,label:'Specchio',action:'atticMirror'}]}
};
let dialogueDone=null;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function showScreen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active')}
function save(){localStorage.setItem(SAVE,JSON.stringify({...state,timer:null,eventTimer:null,audio:null,eventsSeen:[...state.eventsSeen]}))}
function renderRoom(){const r=rooms[state.scene];$('#sceneLayer').dataset.scene=state.scene;$('#chapterText').textContent=r.chapter;$('#roomName').textContent=r.name;$('#objectiveText').textContent=r.objective();$('#hotspots').innerHTML=r.hotspots.map(h=>`<button class="hotspot" style="left:${h.x}%;top:${h.y}%" data-action="${h.action}" data-label="${h.label}" aria-label="${h.label}"></button>`).join('');$('#inventoryItems').textContent=state.items.length?state.items.join(' · '):'Vuoto';$('#tensionBar').style.width=`${Math.min(100,state.tension)}%`;save()}
function addItem(item){if(!state.items.includes(item)){state.items.push(item);tone(520,.18,.08,'sine');renderRoom()}}
function removeItem(item){state.items=state.items.filter(x=>x!==item);renderRoom()}
function has(item){return state.items.includes(item)}
function say(speaker,text,cb){$('#speaker').textContent=speaker;$('#dialogueText').textContent=text;$('#dialogue').classList.remove('hidden');dialogueDone=cb||null;playVoice(text,speaker)}
function closeDialogue(){stopVoice();$('#dialogue').classList.add('hidden');const cb=dialogueDone;dialogueDone=null;if(cb)cb()}
function playVoice(text,speaker){if(state.muted||!('speechSynthesis'in window))return;speechSynthesis.cancel();const chunks=text.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[text];let i=0,keepAlive;const next=()=>{clearInterval(keepAlive);if(i>=chunks.length)return;const u=new SpeechSynthesisUtterance(chunks[i++].trim());u.lang='it-IT';u.rate=speaker==='Clara'?.76:.8;u.pitch=speaker==='Clara'?.84:.62;u.volume=.9;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang?.toLowerCase().startsWith('it'))||null;u.onend=()=>setTimeout(next,140);u.onerror=()=>setTimeout(next,140);speechSynthesis.speak(u);keepAlive=setInterval(()=>{if(speechSynthesis.speaking){speechSynthesis.pause();speechSynthesis.resume()}},9000)};next()}
function stopVoice(){if('speechSynthesis'in window)speechSynthesis.cancel();$('#voiceAudio').pause()}
function inspect(title,text,actions=[]){$('#inspectTitle').textContent=title;$('#inspectText').textContent=text;$('#inspectActions').innerHTML=actions.map((a,i)=>`<button class="action ${a.secondary?'secondary':''}" data-inspect-action="${i}">${a.label}</button>`).join('');$('#inspectModal').classList.remove('hidden');$('#sceneLayer').classList.add('zooming');$('#inspectActions').onclick=e=>{const b=e.target.closest('[data-inspect-action]');if(b)actions[+b.dataset.inspectAction].run()}}
function closeInspect(){$('#inspectModal').classList.add('hidden');$('#sceneLayer').classList.remove('zooming')}
function puzzle(title,text,answer,onSuccess,guard){if(guard&&!guard())return;$('#puzzleTitle').textContent=title;$('#puzzleText').textContent=text;$('#puzzleContent').innerHTML='<input id="puzzleInput" autocomplete="off"><button id="solvePuzzle">CONFERMA</button>';$('#puzzleFeedback').textContent='';$('#puzzleModal').classList.remove('hidden');setTimeout(()=>$('#puzzleInput').focus(),50);$('#solvePuzzle').onclick=()=>{const value=$('#puzzleInput').value.trim().toLowerCase().replace(/\s/g,'');if(value===answer.toLowerCase().replace(/\s/g,'')){tone(660,.3,.1,'sine');$('#puzzleFeedback').textContent='Il meccanismo si sblocca.';setTimeout(()=>{closePuzzle();onSuccess()},600)}else{$('#puzzleFeedback').textContent='Risposta errata. Qualcosa si muove dietro di te.';raiseFear(9);shake();setTimeout(()=>horrorEvent('shadow'),350)}}}
function closePuzzle(){$('#puzzleModal').classList.add('hidden')}
function shake(){const s=$('#sceneLayer');s.classList.remove('shake');void s.offsetWidth;s.classList.add('shake')}
function locked(text='La porta è ancora bloccata.'){const n=$('#lockNotice');n.textContent=text;n.classList.remove('hidden');void n.offsetWidth;setTimeout(()=>n.classList.add('hidden'),1850);tone(62,.4,.12,'sawtooth');raiseFear(4);shake()}
async function transitionTo(next){stopVoice();clearTimeout(state.eventTimer);const t=$('#transition');t.classList.remove('hidden');void t.offsetWidth;t.classList.add('new-scene');tone(78,1.4,.09,'sawtooth');await sleep(2200);state.scene=next;state.lastInput=Date.now();renderRoom();await sleep(2500);t.classList.add('hidden');t.classList.remove('new-scene');scheduleHorror();const lines={parlor:['Clara','Il salotto ricorda ogni voce che ha ascoltato. Non lasciare che impari anche la tua.'],corridor:['Narratore','La porta si chiude alle tue spalle. Il corridoio è più lungo di quanto dovrebbe essere.'],nursery:['Clara','Questa era la mia stanza. La bambola, invece, dice che apparteneva a lei.'],attic:['Narratore','Sopra di te non dovrebbe esserci un altro piano. Eppure la soffitta continua a respirare.']};if(lines[next])say(...lines[next])}
function raiseFear(n){state.tension=Math.min(100,state.tension+n);$('#tensionBar').style.width=`${state.tension}%`}
function initAudio(){if(state.audio)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=new C(),master=ctx.createGain(),osc=ctx.createOscillator(),gain=ctx.createGain(),lfo=ctx.createOscillator(),lfoGain=ctx.createGain();master.gain.value=.055;osc.type='sine';osc.frequency.value=43;gain.gain.value=.65;lfo.frequency.value=.07;lfoGain.gain.value=6;lfo.connect(lfoGain).connect(osc.frequency);osc.connect(gain).connect(master).connect(ctx.destination);osc.start();lfo.start();state.audio={ctx,master,osc,lfo}}
function tone(f=100,d=.25,v=.1,type='sine'){if(state.muted||!state.audio)return;const {ctx}=state.audio,o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+d);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+d)}
function flash(){const l=$('#lightning');l.classList.remove('flash');void l.offsetWidth;l.classList.add('flash');tone(48,.9,.12,'sawtooth')}
function horrorEvent(forced){if($('.modal:not(.hidden)')||!$('#dialogue').classList.contains('hidden')){scheduleHorror();return}const possible=['lightning','knock','shadow','whisper','doll'];let type=typeof forced==='string'?forced:possible[Math.floor(Math.random()*possible.length)];if(type==='lightning'){flash();raiseFear(3)}if(type==='knock'){tone(72,.12,.17,'square');setTimeout(()=>tone(64,.16,.15,'square'),320);raiseFear(5)}if(type==='shadow'){const sh=$('#horrorShadow');sh.classList.remove('walk');void sh.offsetWidth;sh.classList.add('walk');raiseFear(8)}if(type==='whisper'){say('Sussurro',state.scene==='nursery'?'Non era Clara nella culla.':'Non aprire la prossima porta.');raiseFear(7)}if(type==='doll'){const layer=$('#sceneLayer');layer.classList.add('event-doll');shake();setTimeout(()=>layer.classList.remove('event-doll'),1500);raiseFear(6)}scheduleHorror()}
function scheduleHorror(){clearTimeout(state.eventTimer);state.eventTimer=setTimeout(()=>horrorEvent(),18000+Math.random()*26000)}
function handleAction(action){state.lastInput=Date.now();
 if(action==='portrait'){if(!state.flags.portraitMoved){inspect('Ritratto della famiglia Vale','Clara non guarda il fotografo. Guarda il bordo sinistro della cornice.',[{label:'Sposta lentamente il quadro',run:()=>{state.flags.portraitMoved=true;closeInspect();shake();say('Narratore','Dietro il ritratto compare una piccola cassaforte. Sul metallo è inciso: “L’anno in cui smise di crescere”.',renderRoom)}}])}else if(!state.flags.safeSolved)puzzle('La cassaforte del ritratto','Inserisci l’anno della scomparsa di Clara. La fotografia nell’atrio è datata ottobre 1974.','1974',()=>{state.flags.safeSolved=true;addItem('Chiave annerita');say('Narratore','La cassaforte si apre. Dentro riposa una chiave annerita, ancora tiepida.')});else inspect('Cassaforte aperta','È vuota. Sul fondo qualcuno ha inciso: “La prima porta mente”.')}
 if(action==='doll'){raiseFear(8);shake();say('Clara','Non guardarla negli occhi. La prossima volta potrebbe essere più vicina.')}
 if(action==='foyerDoor'){if(!state.flags.safeSolved||!has('Chiave annerita'))return locked('La serratura richiede la chiave nascosta dietro il ritratto.');inspect('Porta del salotto','La chiave annerita entra nella serratura. Dall’altra parte qualcuno trattiene il respiro.',[{label:'Usa la chiave ed entra',run:()=>{closeInspect();removeItem('Chiave annerita');state.flags.foyerSolved=true;transitionTo('parlor')}}])}
 if(action==='curtain'){if(!state.flags.crankTaken){inspect('Dietro la tenda','La finestra è murata. Nel tessuto è impigliata una manovella di ottone.',[{label:'Raccogli la manovella',run:()=>{state.flags.crankTaken=true;addItem('Manovella del grammofono');closeInspect();horrorEvent('knock')}}])}else inspect('Finestra murata','Tra i mattoni filtra aria gelida. La tenda continua a muoversi.')}
 if(action==='record'){if(!has('Manovella del grammofono'))return inspect('Grammofono incompleto','Il cilindro è fermo: manca la manovella laterale.');if(!state.flags.recordPlayed){state.flags.recordPlayed=true;say('Narratore','Inserisci la manovella. Il disco comincia a girare al contrario e pronuncia lentamente: A-R-U-T-R-E-P-A.',()=>renderRoom())}else if(!state.flags.recordSolved)puzzle('Il disco al contrario','Scrivi nel verso corretto la parola “ARUTREPA”.','apertura',()=>{state.flags.recordSolved=true;addItem('Sigillo del corridoio');say('Clara','Hai sentito anche tu la seconda voce? Non apparteneva al disco.')});else inspect('Grammofono silenzioso','La puntina è spezzata. Il messaggio è già stato decifrato.')}
 if(action==='parlorDoor'){if(!state.flags.recordSolved||!has('Sigillo del corridoio'))return locked('La porta non ha una serratura. Al centro manca un sigillo circolare.');inspect('Porta sigillata','Il frammento ricavato dal disco coincide con l’incavo.',[{label:'Inserisci il sigillo',run:()=>{closeInspect();removeItem('Sigillo del corridoio');state.flags.parlorSolved=true;transitionTo('corridor')}}])}
 if(action==='frames'){state.flags.symbolsRead=true;inspect('I quadri del corridoio','Tre cornici mostrano numeri quasi cancellati: III, 0, IX. Sotto è scritto: “Prima la nascita, poi il vuoto, infine la morte”.');renderRoom()}
 if(action==='shadow'){state.flags.shadowSeen=true;raiseFear(10);horrorEvent('shadow');say('Voce sconosciuta','Tre. Zero. Nove. Clara non è la bambina che devi salvare.')}
 if(action==='corridorDoor'){if(!state.flags.symbolsRead)return locked('Tre simboli sulla porta attendono di essere compresi. Esamina i quadri.');if(!state.flags.corridorSolved)return puzzle('La porta della nursery','Inserisci i tre numeri mostrati dalle cornici, nello stesso ordine.','309',()=>{state.flags.corridorSolved=true;addItem('Chiave della nursery');say('Narratore','Le catene cadono sul pavimento. La porta ora riconosce la tua presenza.')});if(!has('Chiave della nursery'))return locked();inspect('Ingresso della nursery','La serratura si apre soltanto con la chiave appena liberata.',[{label:'Entra nella nursery',run:()=>{closeInspect();removeItem('Chiave della nursery');transitionTo('nursery')}}])}
 if(action==='nurseryDoll'){state.flags.dollClue=true;raiseFear(6);inspect('Bambola senza nome','Sul vestito sono cuciti i numeri 3, 9 e 12. Quando distogli lo sguardo, la testa si inclina verso l’orologio.');renderRoom()}
 if(action==='bed'){if(!state.flags.lullabyTaken){inspect('Sotto il letto','Trovi una ninna nanna: “Tre rintocchi quando chiudeva la porta. Nove quando lui arrivava. Dodici quando la casa si svegliava.”',[{label:'Raccogli il foglio',run:()=>{state.flags.lullabyTaken=true;addItem('Ninna nanna strappata');closeInspect();flash()}}])}else inspect('Sotto il letto','Sul pavimento ci sono graffi recenti, come se qualcosa venisse trascinato fuori ogni notte.')}
 if(action==='clock'){if(!state.flags.dollClue||!state.flags.lullabyTaken)return locked('Non conosci ancora la sequenza completa. Esamina la bambola e cerca sotto il letto.');if(!state.flags.clockSolved)puzzle('L’orologio della nursery','Inserisci in sequenza i rintocchi indicati dalla ninna nanna.','3912',()=>{state.flags.clockSolved=true;addItem('Chiave d’argento');say('Narratore','Le lancette ripartono. Sopra il soffitto, una botola si apre con un colpo secco.')});else inspect('Orologio in movimento','Le lancette girano all’indietro, ma il meccanismo della botola è ormai sbloccato.')}
 if(action==='nurseryDoor'){if(!state.flags.clockSolved||!has('Chiave d’argento'))return locked('La botola è collegata al meccanismo dell’orologio.');inspect('Scala della soffitta','La chiave d’argento entra in un piccolo lucchetto sopra la scala.',[{label:'Sali nella soffitta',run:()=>{closeInspect();removeItem('Chiave d’argento');state.flags.nurserySolved=true;transitionTo('attic')}}])}
 if(action==='trunk')inspect('Baule dei Vale','Dentro trovi vestiti da bambina di taglie diverse. Nessuno porta il nome di Clara.',[{label:'Cerca sul fondo',run:()=>{addItem('Registro dei bambini');closeInspect();say('Clara','Non leggere ad alta voce l’ultimo nome.') }}]);
 if(action==='names'){if(!has('Registro dei bambini'))return locked('I cartellini sono troppi. Serve un registro con cui confrontarli.');if(!state.flags.atticSeal)puzzle('Il nome cancellato','Nel registro compaiono Clara, Eleanor e Thomas. Sui cartellini resta un solo nome estraneo: Mara. Scrivilo.','mara',()=>{state.flags.atticSeal=true;addItem('Nome vero: Mara');say('Narratore','Quando pronunci il nome, tutti i cartellini si voltano nello stesso istante. Il primo sigillo è spezzato.')});else inspect('Cartellini immobili','Tutti i nomi sono diventati illeggibili, tranne Mara.')}
 if(action==='atticMirror'){raiseFear(12);flash();say('Voce nello specchio',state.flags.atticSeal?'Hai spezzato soltanto il primo sigillo. La casa ne custodisce altri.':'Il tuo riflesso muove le labbra prima di te.')}
}
function startTimer(){clearInterval(state.timer);state.timer=setInterval(()=>{state.time--;const m=Math.floor(Math.max(0,state.time)/60),s=Math.max(0,state.time)%60;$('#timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;if(state.time%30===0)save();if([2700,1800,900,300,60].includes(state.time)){raiseFear(8);horrorEvent(state.time<=300?'whisper':'knock')}if(state.time<=0){clearInterval(state.timer);say('Narratore','Il tempo è finito. Tutte le porte si chiudono nello stesso istante. La casa ha scelto chi resterà.')}},1000)}
$('#readyCheck').onchange=e=>$('#startButton').disabled=!e.target.checked;
$('#startButton').onclick=()=>{initAudio();showScreen('playScreen');renderRoom();startTimer();scheduleHorror();setTimeout(()=>say('Clara','Se stai ascoltando questa registrazione, la casa ti ha già lasciato entrare. Non fidarti delle stanze. Non fidarti delle porte. E qualunque cosa accada, non permettere alla bambola di vederti uscire.'),500)};
$('#hotspots').onclick=e=>{const b=e.target.closest('[data-action]');if(b)handleAction(b.dataset.action)};
$('#continueDialogue').onclick=closeDialogue;$('#closeInspect').onclick=closeInspect;$('#closePuzzle').onclick=closePuzzle;
$('#soundButton').onclick=()=>{state.muted=!state.muted;$('#soundButton').textContent=state.muted?'🔇':'🔊';if(state.audio)state.audio.master.gain.value=state.muted?0:.055;if(state.muted)stopVoice()};
['pointerdown','keydown','touchstart'].forEach(ev=>addEventListener(ev,()=>state.lastInput=Date.now(),{passive:true}));
setInterval(()=>{if($('#playScreen').classList.contains('active')&&Date.now()-state.lastInput>26000){state.lastInput=Date.now();horrorEvent(Math.random()>.5?'knock':'shadow')}},5000);
