const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const SAVE="heldroom-ashwood-v2";
const initial=()=>({scene:"gate",previous:null,time:3600,started:false,muted:false,hints:4,hintsUsed:0,solved:[],items:[],selected:[],route:null,flags:{grave:false,portrait:false,phonograph:false,candle:false,falseKey:false,childSaved:false,mirrorBroken:false},eventLevel:0});
let state=initial(),timerId,audioCtx,ambient=[],dialogueCallback,introStop=false;
const scenes={
gate:{ch:"I",name:"Il cancello di Ashwood",desc:"La pioggia cancella le tue impronte. Il cancello è serrato da un lucchetto a quattro cifre.",obj:"Entra nella proprietà",hint:"La lapide riporta l'anno in cui Clara smise di crescere.",actions:[["Leggi la lapide","grave"],["Esamina il lucchetto","p_gate"]]},
path:{ch:"I",name:"Il sentiero dei salici",desc:"Tra gli alberi pendono campanelli arrugginiti. Uno suona anche quando il vento si ferma.",obj:"Raggiungi la villa",hint:"Ripeti il ritmo dei campanelli dal più grave al più acuto.",actions:[["Ascolta i campanelli","p_bells"],["Fruga nel fango","mud"]]},
porch:{ch:"II",name:"Il portico",desc:"La porta principale è murata dall'interno. Una fotografia bruciata è inchiodata al legno.",obj:"Trova un ingresso",hint:"Nella fotografia manca una persona, ma la sua ombra è rimasta.",actions:[["Studia la fotografia","p_photo"],["Controlla la finestra","window"]]},
foyer:{ch:"II",name:"L'atrio senza luce",desc:"Il lampadario oscilla. Un ritratto di famiglia ha gli occhi cancellati con la cera.",obj:"Apri il passaggio dietro il ritratto",hint:"Conta soltanto i membri il cui riflesso compare nel vetro.",actions:[["Esamina il ritratto","p_portrait"],["Apri l'ombrelliera","umbrella"],["Segui il pianto","to_parlor"]]},
parlor:{ch:"III",name:"Il salotto del grammofono",desc:"Un disco gira senza puntina. Le tende respirano come polmoni.",obj:"Decifra il messaggio inciso",hint:"Ascolta le parole al contrario: la casa ama gli specchi.",actions:[["Aziona il grammofono","p_record"],["Apri il mobile bar","bar"],["Vai alla biblioteca","to_library"]]},
library:{ch:"III",name:"La biblioteca murata",desc:"I libri sono cuciti con filo nero. Quattro volumi sporgono dallo scaffale.",obj:"Apri la porta segreta",hint:"Le iniziali dei titoli formano la parola VELA.",actions:[["Ordina i libri","p_books"],["Leggi il diario","diary"],["Torna al salotto","to_parlor"]]},
nursery:{ch:"IV",name:"La nursery",desc:"Una bambola siede al centro del tappeto. L'orologio segna le 03:09.",obj:"Trova ciò che Clara nascose",hint:"La ninna nanna indica tre, nove e dodici.",actions:[["Avvicinati alla bambola","doll"],["Regola l'orologio","p_clock"],["Guarda sotto il letto","bed"]]},
attic:{ch:"IV",name:"La soffitta dei nomi",desc:"Centinaia di cartellini portano nomi di bambini. Alcuni sono ancora caldi.",obj:"Trova il vero nome della presenza",hint:"Scarta i nomi ripetuti nel diario: quello rimasto appartiene alla cosa.",actions:[["Confronta i cartellini","p_names"],["Apri il baule","trunk"],["Scendi in nursery","to_nursery"]]},
kitchen:{ch:"V",name:"La cucina carbonizzata",desc:"Il forno è freddo, ma sul tavolo la cera cola verso l'alto.",obj:"Prepara una luce consacrata",hint:"Combina candela, sale e fiammiferi.",actions:[["Cerca nei cassetti","kitchenSearch"],["Esamina il forno","p_oven"],["Vai nel corridoio","to_hall"]]},
hall:{ch:"V",name:"Il corridoio degli specchi",desc:"Ogni specchio mostra una versione diversa del corridoio. In uno, tu non ci sei.",obj:"Attraversa senza seguire il falso riflesso",hint:"Scegli lo specchio che non ripete i tuoi movimenti.",actions:[["Confronta i riflessi","p_mirrors"],["Rompi uno specchio","breakMirror"],["Torna in cucina","to_kitchen"]]},
basement:{ch:"VI",name:"Il seminterrato allagato",desc:"L'acqua nera arriva alle caviglie. Una scatola musicale suona sotto la superficie.",obj:"Riattiva il quadro elettrico",hint:"Rosso, nero, bianco: l'ordine è scritto sul retro della fotografia.",actions:[["Ripara i cavi","p_wires"],["Recupera la scatola","musicBox"],["Sali nel corridoio","to_hall"]]},
cellar:{ch:"VI",name:"La cantina delle candele",desc:"Dodici candele circondano una sedia vuota. Tre fiamme bruciano di colore blu.",obj:"Apri la cripta",hint:"Spegni le candele che corrispondono ai rintocchi della ninna nanna.",actions:[["Spegni le candele","p_candles"],["Esamina la sedia","chair"],["Torna al seminterrato","to_basement"]]},
crypt:{ch:"VII",name:"La cripta di Clara",desc:"La tomba è vuota. Dietro la lastra, una bambina sussurra il tuo nome.",obj:"Decidi di chi fidarti",hint:"Il medaglione appartiene a Clara. La chiave nera appartiene alla casa.",actions:[["Offri il medaglione","route_clara"],["Usa la chiave nera","route_house"],["Leggi l'iscrizione","inscription"]]},
chapel:{ch:"VII",name:"La cappella sotterranea",desc:"La bambola è legata all'altare. Il soffitto si piega verso di te.",obj:"Completa il rituale",hint:"Protezione, memoria, fuoco. L'ordine cambia se hai seguito la casa.",actions:[["Prepara il cerchio","p_ritual"],["Ascolta Clara","claraFinal"]]},
escape:{ch:"VIII",name:"La casa che corre",desc:"Le stanze si piegano una dentro l'altra. La porta d'uscita appare e scompare.",obj:"Fuggi prima che Ashwood si richiuda",hint:"Ricorda il percorso: cancello, salici, portico, atrio.",actions:[["Ricostruisci il percorso","p_escape"],["Voltati","turnAround"]]}};
const puzzles={
p_gate:{title:"Il lucchetto del custode",type:"ENIGMA 1",text:"Inserisci l'anno della scomparsa di Clara.",kind:"code",answer:"1974",success:"path",item:"Chiave del cancello"},
p_bells:{title:"Il canto dei salici",type:"ENIGMA 2",text:"Riproduci il ritmo: grave, medio, acuto, medio.",kind:"choice",choices:["1-2-3-2","3-2-1-2","1-3-2-1"],answer:"1-2-3-2",success:"porch",item:"Campanello spezzato"},
p_photo:{title:"La persona cancellata",type:"ENIGMA 3",text:"Quante ombre compaiono dietro le quattro persone?",kind:"code",answer:"5",success:"foyer",item:"Fotografia bruciata"},
p_portrait:{title:"La famiglia senza occhi",type:"ENIGMA 4",text:"Nel vetro appaiono padre, madre e Clara. Quale numero apre il pannello?",kind:"code",answer:"3",success:"nursery",item:"Medaglione di Clara"},
p_record:{title:"Il disco al contrario",type:"ENIGMA SECONDARIO",text:"Il disco sussurra: «ARUTREPA». Quale parola nasconde?",kind:"text",answer:"apertura",item:"Frammento di cilindro"},
p_books:{title:"Lo scaffale cucito",type:"ENIGMA 5",text:"Premi i libri nell'ordine suggerito: Vento, Eco, Luna, Acqua.",kind:"choice",choices:["VELA","LEVA","VALE"],answer:"VELA",success:"attic",item:"Diario di Eleanor"},
p_clock:{title:"L'orologio della ninna nanna",type:"ENIGMA 6",text:"Inserisci in sequenza i tre rintocchi.",kind:"code",answer:"3912",success:"kitchen",item:"Chiave d'argento"},
p_names:{title:"Il nome che non appartiene",type:"ENIGMA 7",text:"Clara, Eleanor e Thomas compaiono nel diario. Quale nome resta?",kind:"choice",choices:["Mara","Clara","Thomas"],answer:"Mara",item:"Nome vero: Mara"},
p_oven:{title:"Le piastrelle del forno",type:"ENIGMA SECONDARIO",text:"Le piastrelle mostrano luna, occhio, fiamma. Scegli il simbolo che distrugge l'ombra.",kind:"choice",choices:["Luna","Occhio","Fiamma"],answer:"Fiamma",item:"Fiammiferi asciutti"},
p_mirrors:{title:"Il riflesso indipendente",type:"ENIGMA 8",text:"Quale specchio non segue i tuoi movimenti?",kind:"choice",choices:["Sinistro","Centrale","Destro"],answer:"Centrale",success:"basement",item:"Scheggia di specchio"},
p_wires:{title:"Il quadro sommerso",type:"ENIGMA 9",text:"Inserisci le iniziali dei cavi nell'ordine corretto.",kind:"text",answer:"rnb",success:"cellar",item:"Fusibile antico"},
p_candles:{title:"I dodici posti",type:"ENIGMA 10",text:"Quali candele devi spegnere?",kind:"choice",choices:["3, 9, 12","1, 6, 11","2, 7, 10"],answer:"3, 9, 12",success:"crypt",item:"Cera consacrata"},
p_ritual:{title:"Il rituale di Ashwood",type:"ENIGMA 11",text:"Scegli l'ordine dei tre gesti.",kind:"choice",choices:["Sale → Medaglione → Fuoco","Fuoco → Chiave → Sangue","Specchio → Nome → Buio"],answerFn:()=>state.route==="house"?"Fuoco → Chiave → Sangue":"Sale → Medaglione → Fuoco",success:"escape"},
p_escape:{title:"La memoria della casa",type:"ENIGMA FINALE",text:"Seleziona il percorso iniziale nell'ordine corretto.",kind:"choice",choices:["Cancello → Salici → Portico → Atrio","Atrio → Portico → Salici → Cancello","Cancello → Atrio → Cantina → Cripta"],answer:"Cancello → Salici → Portico → Atrio",finish:true}};
const intro=["Ottobre, 1974.","La famiglia Vale scomparve dalla villa di Ashwood.","La polizia trovò soltanto una bambola, seduta davanti alla nursery.","Questa notte una voce registrata ti ha chiamato per nome.","Hai sessanta minuti per spezzare il legame.","Dopo, la casa sceglierà chi resterà."];
function screen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active')}
function initAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();ambientStart()}
function ambientStart(){ambient.forEach(n=>{try{n.stop?.();n.disconnect()}catch{}});ambient=[];if(state.muted||!audioCtx)return;const master=audioCtx.createGain();master.gain.value=.055;master.connect(audioCtx.destination);const osc=audioCtx.createOscillator(),g=audioCtx.createGain();osc.type='sine';osc.frequency.value=state.scene==='chapel'?38:46;g.gain.value=.6;osc.connect(g).connect(master);osc.start();const lfo=audioCtx.createOscillator(),lg=audioCtx.createGain();lfo.frequency.value=.08;lg.gain.value=7;lfo.connect(lg).connect(osc.frequency);lfo.start();ambient=[osc,lfo,master]}
function tone(f=100,d=.3,v=.14,type='sawtooth'){if(state.muted||!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}
function pickVoice(){const v=speechSynthesis.getVoices();return v.find(x=>/it-IT/i.test(x.lang)&&/Elsa|Isabella|Federica|Google|Microsoft/i.test(x.name))||v.find(x=>x.lang?.startsWith('it'))}
function speak(text,who='Narratore'){if(state.muted)return;const file={"Clara-intro":"audio/clara-intro.mp3","Clara-finale":"audio/clara-finale.mp3"}[who];if(file){const a=$('#voiceTrack');a.src=file;a.play().catch(()=>synth(text,who));return}synth(text,who)}
function synth(text,who){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='it-IT';u.voice=pickVoice();u.rate=who==='Clara'?.72:.76;u.pitch=who==='Clara'?.82:.58;u.volume=.9;speechSynthesis.speak(u)}
const wait=ms=>new Promise(r=>setTimeout(r,ms));async function playIntro(){introStop=false;screen('intro');for(const line of intro){if(introStop)break;$('#introText').textContent=line;speak(line,line===intro[0]?'Narratore':'Clara');await wait(Math.max(2300,line.length*65));$('#introText').textContent='';await wait(350)}begin()}
function begin(){if(state.started)return;introStop=true;speechSynthesis.cancel();state.started=true;screen('game');render();startTimer();flash();setTimeout(()=>dialogue('Narratore','Il cancello si è chiuso. Ashwood ora conosce il suono del tuo respiro.'),600);save()}
function startTimer(){clearInterval(timerId);timerId=setInterval(()=>{state.time--;renderTimer();if(state.time%20===0)save();if([2700,1800,900,300,60].includes(state.time))horrorEvent(true);if(state.time<=0)finish(false)},1000);renderTimer()}
function renderTimer(){const m=Math.floor(Math.max(0,state.time)/60),s=Math.max(0,state.time)%60;$('#timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#timer').classList.toggle('danger',state.time<=300)}
function render(){const sc=scenes[state.scene];$('#scene').dataset.scene=state.scene;$('#chapter').textContent=`CAPITOLO ${sc.ch}`;$('#sceneName').textContent=sc.name;$('#sceneDescription').textContent=sc.desc;$('#objective').textContent=sc.obj;$('#progress').textContent=`${state.solved.length}/16`;$('#hints').textContent=state.hints;$('#back').disabled=!state.previous;$('#actions').innerHTML=sc.actions.map(([label,a])=>`<button data-action="${a}">${label}</button>`).join('');renderItems();ambientStart();save();$('#scene').classList.add('moving');setTimeout(()=>$('#scene').classList.remove('moving'),1200)}
function renderItems(){const el=$('#items');el.innerHTML=state.items.length?state.items.map(i=>`<button class="item ${state.selected.includes(i)?'selected':''}" data-item="${i}">${i}</button>`).join(''):'<span class="small">Vuoto</span>'}
function addItem(i){if(!state.items.includes(i)){state.items.push(i);tone(540,.2,.1,'sine');renderItems();toast(`Oggetto raccolto: ${i}`)}}
function toast(t){const e=$('#eventToast');e.textContent=t;e.classList.remove('hidden','show');void e.offsetWidth;e.classList.add('show');setTimeout(()=>e.classList.add('hidden'),4100)}
function dialogue(who,text,cb=null){$('#speaker').textContent=who;$('#dialogueText').textContent=text;$('#dialogue').classList.remove('hidden');dialogueCallback=cb;speak(text,who)}
function flash(){const f=$('#flash');f.classList.remove('active');void f.offsetWidth;f.classList.add('active')}
function scare(text='NON VOLTARTI'){tone(45,.7,.3);$('#scareFace').textContent=text;$('#jumpscare').classList.remove('active');void $('#jumpscare').offsetWidth;$('#jumpscare').classList.add('active');if(navigator.vibrate)navigator.vibrate([100,60,220])}
function go(next){state.previous=state.scene;state.scene=next;flash();render();if(Math.random()<.38)horrorEvent()}
function openPuzzle(id){const p=puzzles[id];if(state.solved.includes(id)){toast('Questo enigma è già risolto.');return}$('#puzzleType').textContent=p.type;$('#puzzleTitle').textContent=p.title;$('#puzzleDescription').textContent=p.text;$('#feedback').textContent='';let body='';if(p.kind==='code')body=`<div class="code">${[...Array(p.answer.length)].map((_,i)=>`<input maxlength="1" data-code="${i}">`).join('')}</div><button class="solve" data-submit="${id}">CONFERMA</button>`;if(p.kind==='text')body=`<input id="textAnswer" autocomplete="off" placeholder="Scrivi la risposta"><button class="solve" data-submit="${id}">CONFERMA</button>`;if(p.kind==='choice')body=`<div class="choices">${p.choices.map(c=>`<button data-choice="${id}" data-value="${c}">${c}</button>`).join('')}</div>`;$('#puzzleBody').innerHTML=body;$('#modal').classList.remove('hidden')}
function solve(id,value){const p=puzzles[id],answer=p.answerFn?p.answerFn():p.answer;if(String(value).trim().toLowerCase()===String(answer).trim().toLowerCase()){state.solved.push(id);if(p.item)addItem(p.item);$('#feedback').textContent='Corretto. Qualcosa si è mosso nella casa.';tone(180,.55,.15);setTimeout(()=>{$('#modal').classList.add('hidden');if(p.finish)finish(true);else if(p.success)go(p.success);else render()},800)}else{$('#feedback').textContent='La casa rifiuta la risposta.';tone(62,.35,.16);if(Math.random()<.45)scare('SBAGLIATO')}}
function combine(){const [a,b]=state.selected,has=x=>[a,b].includes(x);let made=null;if(has('Candela nera')&&has('Fiammiferi asciutti'))made='Candela accesa';if((has('Candela accesa')&&has('Sale consacrato'))||(has('Candela nera')&&has('Sale consacrato')))made='Luce consacrata';if(has('Scheggia di specchio')&&has('Campanello spezzato'))made='Amuleto riflettente';if(made){state.items=state.items.filter(x=>x!==a&&x!==b);state.selected=[];addItem(made);toast('Hai combinato due oggetti.')}else{state.selected=[];toast('Questi oggetti non reagiscono.')}renderItems();save()}
function generic(a){const map={grave:()=>{state.flags.grave=true;dialogue('Narratore','CLARA VALE, 1966–1974. La terra davanti alla lapide è stata smossa da poco.')},mud:()=>addItem('Chiave nera'),window:()=>go('foyer'),umbrella:()=>addItem('Sale consacrato'),to_parlor:()=>go('parlor'),bar:()=>addItem('Candela nera'),to_library:()=>go('library'),diary:()=>addItem('Pagina del diario'),doll:()=>{scare('LEI TI VEDE');addItem('Medaglione di Clara')},bed:()=>addItem('Ninna nanna strappata'),trunk:()=>addItem('Falso certificato'),to_nursery:()=>go('nursery'),kitchenSearch:()=>{addItem('Sale consacrato');addItem('Candela nera')},to_hall:()=>go('hall'),breakMirror:()=>{state.flags.mirrorBroken=true;scare('DIETRO DI TE')},to_kitchen:()=>go('kitchen'),musicBox:()=>addItem('Scatola musicale'),to_basement:()=>go('basement'),chair:()=>dialogue('Clara','Non sederti. È così che lei entra.'),inscription:()=>dialogue('Narratore','Una vita offerta volontariamente apre la porta. Un nome vero la chiude.'),claraFinal:()=>dialogue('Clara','Non bruciare la bambola finché non pronunci il suo vero nome.'),turnAround:()=>scare('TROPPO TARDI')};if(map[a])return map[a]();if(a==='route_clara'){state.route='clara';go('chapel')}if(a==='route_house'){state.route='house';go('chapel')}if(a.startsWith('p_'))openPuzzle(a)}
function horrorEvent(forced=false){state.eventLevel++;const events=['Un passo risuona esattamente dietro di te.','La bambola ha cambiato posizione.','Per un istante, il timer mostra 00:00.','Qualcuno sussurra il tuo nome dalla stanza precedente.','Tutte le porte si chiudono insieme.'];toast(events[Math.floor(Math.random()*events.length)]);if(forced||Math.random()<.25){flash();tone(50,.8,.2);if(Math.random()<.45)scare()}}
function finish(win){clearInterval(timerId);speechSynthesis.cancel();localStorage.removeItem(SAVE);screen('ending');const corrupt=state.route==='house';$('#endKicker').textContent=win?(corrupt?'LA CASA TI HA LASCIATO USCIRE':'IL LEGAME È SPEZZATO'):'IL TEMPO È FINITO';$('#endTitle').textContent=win?(corrupt?'Sei uscito... ma non da solo':'Sei fuggito da Ashwood'):'Ashwood ti ha trattenuto';$('#endText').textContent=win?(corrupt?'La porta si apre. Nel riflesso del vetro, la bambola sorride con il tuo volto.':'Il primo sole attraversa gli alberi. La voce di Clara finalmente tace, libera.'):'Le lancette si fermano. La porta scompare e il tuo nome compare su un cartellino in soffitta.';$('#endTime').textContent=$('#timer').textContent;$('#endPuzzles').textContent=`${state.solved.length}/16`;$('#endRoute').textContent=corrupt?'Corrotto':win?'Liberazione':'Prigioniero'}
function save(){localStorage.setItem(SAVE,JSON.stringify({...state,started:true}))}function load(){try{const x=JSON.parse(localStorage.getItem(SAVE));if(x)state={...initial(),...x,flags:{...initial().flags,...x.flags}}}catch{}}
$('#ready').addEventListener('change',e=>$('#newGame').disabled=!e.target.checked);$('#newGame').onclick=()=>{state=initial();initAudio();playIntro()};$('#continueGame').onclick=()=>{load();initAudio();state.started=true;screen('game');render();startTimer()};$('#skipIntro').onclick=()=>{introStop=true;begin()};$('#dialogueNext').onclick=()=>{$('#dialogue').classList.add('hidden');const c=dialogueCallback;dialogueCallback=null;c?.()};$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#closeHint').onclick=()=>$('#hintModal').classList.add('hidden');$('#audio').onclick=()=>{state.muted=!state.muted;$('#audio').textContent=state.muted?'🔇':'🔊';if(state.muted){speechSynthesis.cancel();ambientStart()}else initAudio()};$('#hint').onclick=()=>{if(!state.hints)return toast('Non hai più aiuti.');state.hints--;state.hintsUsed++;$('#hintText').textContent=scenes[state.scene].hint;$('#hintModal').classList.remove('hidden');render();speak(scenes[state.scene].hint,'Clara')};$('#look').onclick=()=>horrorEvent();$('#back').onclick=()=>{if(state.previous){const x=state.scene;state.scene=state.previous;state.previous=x;render()}};$('#restart').onclick=()=>location.reload();
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a)generic(a.dataset.action);const sub=e.target.closest('[data-submit]');if(sub){const p=puzzles[sub.dataset.submit];let v=p.kind==='code'?$$('[data-code]').map(x=>x.value).join(''):$('#textAnswer').value;solve(sub.dataset.submit,v)}const ch=e.target.closest('[data-choice]');if(ch)solve(ch.dataset.choice,ch.dataset.value);const item=e.target.closest('[data-item]');if(item){const n=item.dataset.item;state.selected=state.selected.includes(n)?state.selected.filter(x=>x!==n):[...state.selected,n].slice(-2);renderItems();if(state.selected.length===2)setTimeout(combine,250)}});
if(localStorage.getItem(SAVE))$('#continueGame').classList.remove('hidden');speechSynthesis?.getVoices();