const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const SAVE='heldroom-living-house-v1';
const fresh=()=>({scene:'foyer',time:3600,muted:false,items:[],fear:10,started:false,lastAction:Date.now(),roomVisits:{foyer:1},lookCounts:{},wrongAnswers:0,eventsSeen:[],flags:{portraitMoved:false,safeVisible:false,safeSolved:false,keyTaken:false,foyerSolved:false,dollGone:false,calendarRead:false,clockRead:false,crankTaken:false,recordSolved:false,parlorSolved:false,symbolsRead:false,corridorSolved:false,lullabyTaken:false,dollClue:false,clockSolved:false,nurserySolved:false,atticSeal:false}});
let state=fresh(),timerId,eventTimer,audioEngine=null,dialogueDone=null,narrationToken=0;
const rooms={
 foyer:{chapter:'CAPITOLO I',name:'L’atrio senza luce',objective:()=>state.flags.safeSolved?'Prendi la chiave e apri la porta':state.flags.safeVisible?'Trova il codice della cassaforte':'Scopri cosa nasconde il ritratto'},
 parlor:{chapter:'CAPITOLO II',name:'Il salotto del grammofono',objective:()=>state.flags.crankTaken?'Completa il grammofono e decifra il messaggio':'Trova la manovella mancante'},
 corridor:{chapter:'CAPITOLO III',name:'Il corridoio delle ombre',objective:()=>state.flags.symbolsRead?'Decifra i simboli della porta':'Trova il codice nascosto nei quadri'},
 nursery:{chapter:'CAPITOLO IV',name:'La nursery di Clara',objective:()=>state.flags.lullabyTaken&&state.flags.dollClue?'Regola l’orologio':'Trova due indizi nella stanza'},
 attic:{chapter:'CAPITOLO V',name:'La soffitta dei nomi',objective:()=>state.flags.atticSeal?'Il primo sigillo è spezzato':'Scopri il vero nome della presenza'}
};
const hotspotMap={
 foyer:[['Ritratto',38,37,'portrait'],['Bambola',60,65,'doll'],['Orologio',55,29,'clock'],['Calendario',55,51,'calendar'],['Porta',80,55,'foyerDoor']],
 parlor:[['Grammofono',29,52,'record'],['Tenda',72,42,'curtain'],['Porta',52,72,'parlorDoor']],
 corridor:[['Quadri',25,44,'frames'],['Ombra',50,48,'shadow'],['Nursery',51,72,'corridorDoor']],
 nursery:[['Bambola',51,66,'nurseryDoll'],['Orologio',70,38,'nurseryClock'],['Letto',25,65,'bed'],['Botola',87,53,'nurseryDoor']],
 attic:[['Baule',28,45,'trunk'],['Cartellini',56,38,'names'],['Specchio',79,62,'atticMirror']]
};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function save(){localStorage.setItem(SAVE,JSON.stringify(state))}
function load(){try{const raw=JSON.parse(localStorage.getItem(SAVE));if(raw)state={...fresh(),...raw,flags:{...fresh().flags,...raw.flags},roomVisits:{foyer:1,...raw.roomVisits},lookCounts:{...raw.lookCounts}}}catch{}}
function showScreen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active')}
function renderRoom(){const r=rooms[state.scene];$('#chapterText').textContent=r.chapter;$('#roomName').textContent=r.name;$('#objectiveText').textContent=r.objective();$('#tensionBar').style.width=`${Math.min(100,state.fear)}%`;$('#inventoryItems').textContent=state.items.length?state.items.join(' · '):'Vuoto';$('#sceneLayer').dataset.scene=state.scene;renderArt();renderHotspots();save()}
function renderArt(){const art=$('#roomArt');art.dataset.room=state.scene;if(state.scene==='foyer'){art.innerHTML=`<div class="foyer-wall"></div><div class="window"></div><div class="curtain left"></div><div class="curtain right"></div><div class="floor"></div><div class="rug"></div><div id="foyerSafe" class="safe ${state.flags.safeVisible?'visible':''} ${state.flags.safeSolved?'open':''}"></div><div id="foyerPortrait" class="portrait ${state.flags.portraitMoved?'moved':''}"></div><div class="clock"></div><div class="calendar"><small>OTTOBRE</small>1974</div><div id="foyerDoorArt" class="door"></div><div id="chandelier" class="chandelier"></div><div id="foyerDoll" class="doll ${state.flags.dollGone?'gone':''}"></div><div class="rain"></div><div class="dust"></div>`}else{art.innerHTML=`<div class="foyer-wall"></div><div class="floor"></div><div class="rug"></div><div class="door"></div><div class="chandelier"></div><div class="dust"></div>`;art.style.background=roomBackground(state.scene)}}
function roomBackground(room){return{parlor:'radial-gradient(circle at 28% 38%,rgba(120,68,38,.2),transparent 20%),linear-gradient(#191214,#050304 76%)',corridor:'linear-gradient(90deg,#090607 0 17%,#1c1114 18% 82%,#080506 83%)',nursery:'radial-gradient(circle at 70% 32%,rgba(155,120,90,.13),transparent 22%),linear-gradient(#181214,#040304 72%)',attic:'radial-gradient(circle at 50% 18%,rgba(110,85,60,.12),transparent 22%),linear-gradient(#17110f,#030303 74%)'}[room]}
function renderHotspots(){const list=hotspotMap[state.scene]||[];$('#hotspots').innerHTML=list.map(([label,x,y,action])=>`<button class="hotspot" style="left:${x}%;top:${y}%" data-action="${action}" data-label="${label}" aria-label="${label}"></button>`).join('')}
function addItem(item){if(!state.items.includes(item)){state.items.push(item);tone(520,.2,.08,'sine');renderRoom()}}
function removeItem(item){state.items=state.items.filter(x=>x!==item);renderRoom()}
const has=item=>state.items.includes(item);
function track(name){state.lastAction=Date.now();state.lookCounts[name]=(state.lookCounts[name]||0)+1;save()}
function raiseFear(n){state.fear=Math.min(100,state.fear+n);$('#tensionBar').style.width=`${state.fear}%`}
function say(speaker,text,cb){narrationToken++;$('#speaker').textContent=speaker;$('#dialogueText').textContent=text;$('#dialogue').classList.remove('hidden');dialogueDone=cb||null;speakComplete(text,speaker,narrationToken)}
function closeDialogue(){narrationToken++;if('speechSynthesis'in window)speechSynthesis.cancel();$('#dialogue').classList.add('hidden');const cb=dialogueDone;dialogueDone=null;if(cb)cb()}
function speakComplete(text,speaker,token){if(state.muted||!('speechSynthesis'in window))return;speechSynthesis.cancel();const chunks=text.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[text];let i=0;const next=()=>{if(token!==narrationToken||i>=chunks.length)return;const u=new SpeechSynthesisUtterance(chunks[i++].trim());u.lang='it-IT';u.rate=speaker==='Clara'?.74:.79;u.pitch=speaker==='Clara'?.82:.62;u.volume=.92;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>/^it/i.test(v.lang)&&/Elsa|Isabella|Federica|Google|Microsoft/i.test(v.name))||voices.find(v=>/^it/i.test(v.lang))||null;u.onend=()=>setTimeout(next,140);u.onerror=()=>setTimeout(next,180);speechSynthesis.speak(u)};next()}
function inspect(title,text,actions=[]){$('#inspectTitle').textContent=title;$('#inspectText').textContent=text;$('#inspectVisual').className='inspect-visual';$('#inspectActions').innerHTML=actions.map((a,i)=>`<button class="action ${a.secondary?'secondary':''}" data-inspect-action="${i}">${a.label}</button>`).join('');$('#inspectModal').classList.remove('hidden');$('#sceneLayer').classList.add('zooming');$('#inspectActions').onclick=e=>{const b=e.target.closest('[data-inspect-action]');if(b)actions[+b.dataset.inspectAction].run()}}
function closeInspect(){$('#inspectModal').classList.add('hidden');$('#sceneLayer').classList.remove('zooming')}
function puzzle(title,text,answer,onSuccess){$('#puzzleTitle').textContent=title;$('#puzzleText').textContent=text;$('#puzzleContent').innerHTML='<input id="puzzleInput" autocomplete="off" inputmode="text"><button id="solvePuzzle">CONFERMA</button>';$('#puzzleFeedback').textContent='';$('#puzzleModal').classList.remove('hidden');setTimeout(()=>$('#puzzleInput').focus(),60);$('#solvePuzzle').onclick=()=>{const v=$('#puzzleInput').value.trim().toLowerCase().replace(/\s/g,'');if(v===answer.toLowerCase().replace(/\s/g,'')){tone(650,.35,.09,'sine');$('#puzzleFeedback').textContent='Il meccanismo cede.';setTimeout(()=>{closePuzzle();onSuccess()},650)}else{state.wrongAnswers++;raiseFear(8);$('#puzzleFeedback').textContent='Risposta errata. Qualcosa si muove dietro di te.';cameraHit();setTimeout(()=>horrorEvent('shadow'),350)}}}
function closePuzzle(){$('#puzzleModal').classList.add('hidden')}
function locked(text){const n=$('#lockNotice');n.textContent=text||'La casa non ti lascia passare.';n.classList.remove('hidden');void n.offsetWidth;setTimeout(()=>n.classList.add('hidden'),1800);tone(63,.45,.12,'sawtooth');raiseFear(4);cameraHit()}
function cameraHit(){const c=$('#camera');c.classList.remove('hit');void c.offsetWidth;c.classList.add('hit')}
function initAudio(){if(audioEngine)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=new C(),master=ctx.createGain();master.gain.value=.08;master.connect(ctx.destination);const drone=ctx.createOscillator(),dg=ctx.createGain();drone.type='sine';drone.frequency.value=42;dg.gain.value=.45;drone.connect(dg).connect(master);drone.start();const noiseBuffer=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),data=noiseBuffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const rain=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),rg=ctx.createGain();rain.buffer=noiseBuffer;rain.loop=true;filter.type='bandpass';filter.frequency.value=1500;filter.Q.value=.45;rg.gain.value=.16;rain.connect(filter).connect(rg).connect(master);rain.start();audioEngine={ctx,master,drone,rain}}
function tone(f=100,d=.25,v=.1,type='sine'){if(state.muted||!audioEngine)return;const{ctx}=audioEngine,o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+d);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+d)}
function flash(){const l=$('#lightning');l.classList.remove('flash');void l.offsetWidth;l.classList.add('flash');tone(48,1,.13,'sawtooth')}
function knock(){tone(72,.13,.16,'square');setTimeout(()=>tone(62,.18,.14,'square'),330)}
function showHint(text){const el=$('#interactionHint');el.textContent=text;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),2200)}
function horrorEvent(forced){if(!state.started||!$('#dialogue').classList.contains('hidden')||$('.modal:not(.hidden)'))return scheduleHorror();const choices=['lightning','knock','shadow','chandelier','doll'];const type=forced||choices[Math.floor(Math.random()*choices.length)];if(type==='lightning'){flash();raiseFear(3)}if(type==='knock'){knock();cameraHit();raiseFear(5)}if(type==='shadow'){const sh=$('#horrorShadow');sh.classList.remove('walk');void sh.offsetWidth;sh.classList.add('walk');raiseFear(8)}if(type==='chandelier'&&state.scene==='foyer'){const c=$('#chandelier');if(c){c.classList.add('wild');setTimeout(()=>c.classList.remove('wild'),1600);raiseFear(5)}}if(type==='doll'&&state.scene==='foyer'&&!state.flags.dollGone){state.flags.dollGone=true;renderRoom();raiseFear(10);showHint('La sedia è vuota.');tone(88,.7,.1,'sine')}state.eventsSeen.push(`${state.scene}:${type}:${Date.now()}`);save();scheduleHorror()}
function scheduleHorror(){clearTimeout(eventTimer);const idle=Date.now()-state.lastAction;const min=idle>22000?9000:18000;eventTimer=setTimeout(()=>horrorEvent(),min+Math.random()*22000)}
async function transitionTo(next){clearTimeout(eventTimer);narrationToken++;if('speechSynthesis'in window)speechSynthesis.cancel();const t=$('#transition');t.classList.remove('hidden');void t.offsetWidth;t.classList.add('new-scene');tone(75,1.5,.1,'sawtooth');await sleep(2250);state.scene=next;state.roomVisits[next]=(state.roomVisits[next]||0)+1;state.lastAction=Date.now();renderRoom();await sleep(2450);t.classList.add('hidden');t.classList.remove('new-scene');scheduleHorror();const lines={parlor:['Clara','Il salotto ricorda ogni voce che ha ascoltato. Non lasciare che impari anche la tua.'],corridor:['Narratore','La porta si chiude alle tue spalle. Il corridoio è più lungo di quanto dovrebbe essere.'],nursery:['Clara','Questa era la mia stanza. La bambola sostiene che appartenesse a lei.'],attic:['Narratore','Sopra la nursery non dovrebbe esserci alcun piano. Eppure la soffitta respira.']};if(lines[next])say(...lines[next])}
function movePortrait(){state.flags.portraitMoved=true;state.flags.safeVisible=true;closeInspect();const p=$('#foyerPortrait');p?.classList.add('moved');setTimeout(()=>{renderRoom();tone(92,.7,.1,'sawtooth');say('Narratore','La cornice scivola con un gemito. Dietro il ritratto compare una cassaforte incassata nel muro.')},850)}
function openSafe(){if(!state.flags.clockRead||!state.flags.calendarRead)return inspect('Cassaforte nel muro','Quattro cilindri attendono un codice. Prima devi capire quale data la casa vuole ricordare.');puzzle('Cassaforte della famiglia Vale','L’orologio è fermo sulle 19:00. Il calendario mostra ottobre 1974. Inserisci l’anno che la casa continua a ripetere.','1974',()=>{state.flags.safeSolved=true;renderRoom();say('Narratore','Il metallo scatta. Dentro la cassaforte riposa una chiave annerita, ancora tiepida.',()=>addItem('Chiave annerita'))})}
function handleAction(a){track(a);
 if(a==='portrait'){if(!state.flags.portraitMoved)return inspect('Ritratto della famiglia Vale','Clara non guarda il fotografo. I suoi occhi indicano il bordo della cornice.',[{label:'Sposta lentamente il quadro',run:movePortrait}]);if(!state.flags.safeSolved)return openSafe();return inspect('Vano aperto','La cassaforte è vuota. Sul fondo è inciso: “La prima porta mente”.')}
 if(a==='clock'){state.flags.clockRead=true;renderRoom();return inspect('Orologio fermo','Le lancette sono bloccate sulle diciannove. Il pendolo continua a muoversi senza produrre alcun suono.')}
 if(a==='calendar'){state.flags.calendarRead=true;renderRoom();return inspect('Calendario strappato','Ottobre 1974. Tutti i giorni sono cancellati tranne il diciassette. Sul retro: “Ricorda l’anno, non il giorno”.')}
 if(a==='doll'){if((state.lookCounts.doll||0)>=3&&!state.flags.dollGone){state.flags.dollGone=true;renderRoom();raiseFear(12);return say('Clara','Hai guardato troppo a lungo. Adesso lei sa che volto usare.')}raiseFear(5);return inspect('Bambola senza nome','Gli occhi di vetro riflettono una porta aperta. Nella stanza, però, la porta è ancora chiusa.')}
 if(a==='foyerDoor'){if(!state.flags.safeSolved||!has('Chiave annerita'))return locked('La serratura richiede la chiave nascosta nella cassaforte.');return inspect('Porta del salotto','La chiave entra perfettamente. Dall’altra parte qualcuno trattiene il respiro.',[{label:'Inserisci la chiave',run:()=>{closeInspect();const d=$('#foyerDoorArt');d?.classList.add('unlocking');tone(105,.4,.12,'square');setTimeout(()=>{removeItem('Chiave annerita');state.flags.foyerSolved=true;transitionTo('parlor')},900)}}])}
 if(a==='curtain'){if(!state.flags.crankTaken)return inspect('Dietro la tenda','La finestra è murata. Nel tessuto è impigliata una manovella di ottone.',[{label:'Raccogli la manovella',run:()=>{state.flags.crankTaken=true;addItem('Manovella del grammofono');closeInspect();knock()}}]);return inspect('Finestra murata','Tra i mattoni filtra aria gelida. La tenda continua a respirare.')}
 if(a==='record'){if(!has('Manovella del grammofono'))return inspect('Grammofono incompleto','Manca la manovella laterale.');if(!state.flags.recordSolved)return puzzle('Il disco al contrario','La voce sul disco pronuncia: ARUTREPA. Scrivila nel verso corretto.','apertura',()=>{state.flags.recordSolved=true;addItem('Sigillo del corridoio');say('Clara','Hai sentito la seconda voce? Non era registrata sul disco.')});return inspect('Grammofono silenzioso','La puntina si è spezzata. Il messaggio è già stato decifrato.')}
 if(a==='parlorDoor'){if(!state.flags.recordSolved||!has('Sigillo del corridoio'))return locked('Al centro della porta manca un sigillo circolare.');removeItem('Sigillo del corridoio');state.flags.parlorSolved=true;return transitionTo('corridor')}
 if(a==='frames'){state.flags.symbolsRead=true;renderRoom();return inspect('Tre cornici','I numeri quasi cancellati sono III, 0 e IX. Sotto: “Prima la nascita, poi il vuoto, infine la morte”.')}
 if(a==='shadow'){horrorEvent('shadow');return say('Voce sconosciuta','Tre. Zero. Nove. Clara non è la bambina che devi salvare.')}
 if(a==='corridorDoor'){if(!state.flags.symbolsRead)return locked('La porta non riconosce ancora il codice. Esamina i quadri.');if(!state.flags.corridorSolved)return puzzle('Porta della nursery','Inserisci i tre numeri mostrati dalle cornici.','309',()=>{state.flags.corridorSolved=true;addItem('Chiave della nursery');say('Narratore','Le catene cadono. La porta ora riconosce la tua presenza.')});if(!has('Chiave della nursery'))return locked();removeItem('Chiave della nursery');return transitionTo('nursery')}
 if(a==='bed'){if(!state.flags.lullabyTaken){state.flags.lullabyTaken=true;addItem('Ninna nanna strappata');renderRoom()}return inspect('Sotto il letto','La ninna nanna ripete tre numeri: tre, nove, dodici.')}
 if(a==='nurseryDoll'){state.flags.dollClue=true;renderRoom();return inspect('Bambola della nursery','Sul vestito sono cuciti 3, 9 e 12. La testa è inclinata verso l’orologio.')}
 if(a==='nurseryClock'){if(!state.flags.lullabyTaken||!state.flags.dollClue)return locked('Non hai ancora raccolto abbastanza indizi.');if(!state.flags.clockSolved)return puzzle('Orologio della ninna nanna','Inserisci i tre numeri nello stesso ordine.','3912',()=>{state.flags.clockSolved=true;addItem('Chiave della soffitta');say('Narratore','Le lancette ripartono. Sopra di te si apre una botola.')});return inspect('Orologio riattivato','Il pendolo oscilla. Ogni rintocco sembra provenire dal soffitto.')}
 if(a==='nurseryDoor'){if(!state.flags.clockSolved||!has('Chiave della soffitta'))return locked('La botola è bloccata da una serratura d’argento.');removeItem('Chiave della soffitta');state.flags.nurserySolved=true;return transitionTo('attic')}
 if(a==='trunk')return inspect('Baule di Eleanor','Dentro trovi un diario. Tre nomi ricorrono: Clara, Eleanor, Thomas.',[{label:'Raccogli il diario',run:()=>{addItem('Diario di Eleanor');closeInspect()}}])
 if(a==='atticMirror'){horrorEvent('shadow');return inspect('Specchio annerito','Il tuo riflesso muove le labbra con un istante di ritardo.')}
 if(a==='names'){if(!has('Diario di Eleanor'))return locked('I cartellini sono troppi. Serve qualcosa con cui confrontarli.');if(!state.flags.atticSeal)return puzzle('Il nome cancellato','Clara, Eleanor e Thomas compaiono nel diario. Tra i cartellini resta un nome estraneo.','mara',()=>{state.flags.atticSeal=true;addItem('Nome vero: Mara');say('Clara','Ora lei sa che conosci il suo nome. Da questo momento la casa smetterà di giocare.')});return inspect('Cartellini immobili','Quello con il nome Mara è diventato nero.')}
}
function startTimer(){clearInterval(timerId);timerId=setInterval(()=>{state.time=Math.max(0,state.time-1);const m=Math.floor(state.time/60),s=state.time%60;$('#timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;if(state.time%20===0)save();if([2700,1800,900,300,60].includes(state.time))horrorEvent('knock');if(state.time===0){clearInterval(timerId);say('Narratore','Il tempo è finito. La casa ha scelto chi resterà.')}},1000)}
function begin(){state.started=true;state.lastAction=Date.now();showScreen('playScreen');initAudio();renderRoom();startTimer();scheduleHorror();setTimeout(()=>say('Clara','Se stai ascoltando questa registrazione, la casa ti ha già lasciato entrare. Non fidarti delle stanze. Non fidarti delle porte. E qualunque cosa accada, non permettere alla bambola di vederti uscire.'),500)}
load();
$('#readyCheck').onchange=e=>$('#startButton').disabled=!e.target.checked;
$('#startButton').onclick=begin;
$('#hotspots').onclick=e=>{const b=e.target.closest('[data-action]');if(b)handleAction(b.dataset.action)};
$('#continueDialogue').onclick=closeDialogue;
$('#closeInspect').onclick=closeInspect;
$('#closePuzzle').onclick=closePuzzle;
$('#soundButton').onclick=()=>{state.muted=!state.muted;$('#soundButton').textContent=state.muted?'🔇':'🔊';if(audioEngine)audioEngine.master.gain.value=state.muted?0:.08;if(state.muted&&'speechSynthesis'in window)speechSynthesis.cancel();save()};
['pointerdown','mousemove','keydown','touchstart'].forEach(ev=>document.addEventListener(ev,()=>state.lastAction=Date.now(),{passive:true}));
